### ISSUE TITLE
Trouble with Install

### ISSUE THREAD

**Issue by diogocaribe** [tsw-apropos/qmarxanz#1]
When I try to install plugin, it doesn't do it. Afterward appered massage called to me that there isn't ogr module.

Thanks
![captura de tela 2015-04-06 23 08 32](https://cloud.githubusercontent.com/assets/7991205/7015913/ea92f68a-dcb1-11e4-8838-d6c4b1d9d8a1.png)

**Comment by aproposinfosystems** [comment]
This issue was identified on the Maraxn mailing list. The following solution has been found.

In QGIS 2.8.1 on windows, there is a file missing in the installation that prevents the system from finding the osgeo library (which is in fact already installed).

The folder in question is (on most systems):
C:\Program Files\QGIS Wien\apps\Python27\Lib\site-packages

Now in this folder there are both other folders and the files for those folder with names such as PIL.pth. What is missing is a file called osgeo.pth.

Create this empty file and put the text osgeo inside it. Nothing else.

Then restart QGIS and if you open your python command you should be able to type in

import ogr

After that try installing the plugin again.
